name : 블루그린 CICD

on:
  push:
    branches:
      - main


jobs:
  # 빌드 및 허브 전송
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v2

      - name: 도커허브 로그인
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: 이미지 빌드 및 전송하기
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/express-healthcheck:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/express-healthcheck:latest

  # 배포하기
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH 설정하기
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: EC2 배포하기
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'bash -s' <<EOF
          set -e
          cd /home/${{ secrets.SERVER_USER }}/bluegreen
          
          if docker ps | grep express-healthcheck-blue; then
            TARGET=green
            STOP=express-healthcheck-blue
          elif docker ps | grep express-healthcheck-green; then
            TARGET=blue
            STOP=express-healthcheck-green
          else
            TARGET=blue
            STOP=none
          fi
          
          echo "배포하는 컨테이너: \$TARGET"
          docker compose pull express-healthcheck-\$TARGET
          docker compose up -d express-healthcheck-\$TARGET
          
          if ["\$STOP" != "none" ]; then
            echo "헬스체크 진행중..."
            for i in {1..10}; do
              sleep 2
              if docker exec express-healthcheck-\$TARGET curl -s http://localhost:3000/heath; then
                echo "헬스체크 성공✅ "
                break
              elif [ \$i -eq 10 ]; then
                echo "헬스체크 실패. 롤백중.."
                docker stop express-healthcheck-\%TARGET
                docker compose restart \$STOP
                exit 1
              fi
            done
          else
            echo "첫 배포 - 헬스체크 스킵"
          fi
          
          echo "스위칭 Nginx to \$TARGET"
          sed -i "s/express-healthcheck-[a-z]\\+/express-healthcheck-\$TARGET/g" nginx.conf
          docker stop nginx-proxy || true
          docker rm -f nginx-proxy || true
          docker compose up -d nginx-proxy

          if [ "\$STOP" != "none" ]; then
            docker stop \$STOP || true
          fi
          EOF
